Repository apache/dubbo-website, pull requests merged in 2019-11, with the labels that each got.

#521 fix (zh_cn) benchmark-tool.md - spelling mistakes
  docs/zh-cn/user/benchmark-tool.md
Labels: first-time-contributor

#514 Fix typos
  blog/en-us/dubbo-101.md
  blog/zh-cn/dubbo-101.md
  blog/zh-cn/dubbo-annotation-driven.md
Labels: first-time-contributor

#515 Update threadpool.md
  docs/zh-cn/dev/impls/threadpool.md
Labels: first-time-contributor

#505 translate config-rule-deprecated.md #368
  docs/en-us/user/demos/config-rule-deprecated.md
Labels: first-time-contributor, status/waiting-for-feedback

#486 WIP Protobuf json doc
  docs/zh-cn/user/demos/GooglePb-generic-reference.md
Labels: status/waiting-for-feedback

#511 完成nacos注册中心的翻译
  blog/en-us/dubbo-registry-nacos-integration.md
Labels: status/waiting-for-feedback

#448 [Blog] add en-us Translation dubbo-basic-usage-dubbo-consumer-configu…
  blog/en-us/dubbo-basic-usage-dubbo-consumer-configuration.md
Labels: status/waiting-for-feedback

#533 在介绍LeastActiveLoadBalance时,有一处笔误。
  docs/zh-cn/source_code_guide/loadbalance.md
Labels: first-time-contributor
